// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fujin-grpc-gateway.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FujinService_Stream_FullMethodName = "/fujin.v1.FujinService/Stream"
)

// FujinServiceClient is the client API for FujinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bidirectional streaming service for async request-response
type FujinServiceClient interface {
	// Bidirectional stream for all operations
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FujinRequest, FujinResponse], error)
}

type fujinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFujinServiceClient(cc grpc.ClientConnInterface) FujinServiceClient {
	return &fujinServiceClient{cc}
}

func (c *fujinServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FujinRequest, FujinResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FujinService_ServiceDesc.Streams[0], FujinService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FujinRequest, FujinResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FujinService_StreamClient = grpc.BidiStreamingClient[FujinRequest, FujinResponse]

// FujinServiceServer is the server API for FujinService service.
// All implementations should embed UnimplementedFujinServiceServer
// for forward compatibility.
//
// Bidirectional streaming service for async request-response
type FujinServiceServer interface {
	// Bidirectional stream for all operations
	Stream(grpc.BidiStreamingServer[FujinRequest, FujinResponse]) error
}

// UnimplementedFujinServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFujinServiceServer struct{}

func (UnimplementedFujinServiceServer) Stream(grpc.BidiStreamingServer[FujinRequest, FujinResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFujinServiceServer) testEmbeddedByValue() {}

// UnsafeFujinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FujinServiceServer will
// result in compilation errors.
type UnsafeFujinServiceServer interface {
	mustEmbedUnimplementedFujinServiceServer()
}

func RegisterFujinServiceServer(s grpc.ServiceRegistrar, srv FujinServiceServer) {
	// If the following call pancis, it indicates UnimplementedFujinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FujinService_ServiceDesc, srv)
}

func _FujinService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FujinServiceServer).Stream(&grpc.GenericServerStream[FujinRequest, FujinResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FujinService_StreamServer = grpc.BidiStreamingServer[FujinRequest, FujinResponse]

// FujinService_ServiceDesc is the grpc.ServiceDesc for FujinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FujinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fujin.v1.FujinService",
	HandlerType: (*FujinServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _FujinService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fujin-grpc-gateway.proto",
}
